# Generated by Django 6.1.1 on 2026-10-08 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=17, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('anio_publicacion', models.PositiveIntegerField()),
                ('cant_total', models.PositiveIntegerField(default=0)),
                ('cant_disponible', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.PositiveIntegerField()),
                ('mail', models.EmailField(max_length=200, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_reserva', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RETIRADA', 'Retirada'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=10)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='biblio.libro')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='biblio.socio')),
            ],
        ),
    ]
